# Generated by Django 5.0.3 on 2024-03-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_username_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emai',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='typ',
        ),
    ]
