# Generated by Django 5.0.3 on 2024-03-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_email_user_emai_rename_password_user_passwor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emai',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passwor',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='typ',
            new_name='type',
        ),
    ]
